In [1]:
import matplotlib.pyplot as plt
from matplotlib import rc  ### 이 줄과
rc('font', family='AppleGothic') 			## 이 두 줄을 
plt.rcParams['axes.unicode_minus'] = False  ## 추가해줍니다. 

import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

df = pd.read_csv("./대전광역시 유성구_지역화폐 발급월별 소비금액 지수 데이터_20220531.csv", encoding='CP949')

df["발급년"]=df["발급년"].astype(str)
df["발급월"]=df["발급월"].astype(str)

for i in range(2,3):
    df["발급월"+str(i)] = df["발급월"].astype('str').str.zfill(i) # 1~9월까지 0을 채워서 두 자리까지..
    
df["발급년월"] = df["발급년"] + df["발급월2"] #컬럼 두 개 합치기 = 2xxx0x 형태로 만들기

from datetime import datetime

df['발급년월']=df['발급년월'].apply(lambda _ : datetime.strptime(_,'%Y%m'))

def change_age(text:str):
    return text[:2]

df['연령대'] = df['연령대'].map(change_age).astype(int)
df.head()

,발급년,발급월,광역시도코드,광역시도명,시군구코드,시군구명,법정동코드,법정동명,연령대,성별,지수_이용건수,지수_이용금액,발급월2,발급년월
0,2020,5,30,대전광역시,30110.0,동구,3011010200,인동,30,여성,100.0,100.0,05,2020-05-01
1,2020,5,30,대전광역시,30110.0,동구,3011010400,천동,40,여성,100.0,100.0,05,2020-05-01
2,2020,5,30,대전광역시,30110.0,동구,3011010500,가오동,30,남성,100.0,100.0,05,2020-05-01
3,2020,5,30,대전광역시,30110.0,동구,3011010500,가오동,40,여성,100.0,100.0,05,2020-05-01
4,2020,5,30,대전광역시,30110.0,동구,3011010600,신흥동,30,남성,100.0,100.0,05,2020-05-01